<?php
/**
 * FaceApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * facial recognition api
 *
 * # Introducão  Seja bem-vindo a documentação da API de Reconhecimento Facial da [HIMNI.COM](https://himni.com)   Nossa API foi criada utilizando o padrão [REST](https://restfulapi.net/) e [HATEOAS](https://restfulapi.net/hateoas/), possibilitando a integração de seu sistema ao nosso, e está documentada abaixo.  # Como usar a API?  Logo a seguir você encontrará todos os recursos e métodos suportados pela API, sendo que essa página possibilita que você teste os recursos e métodos diretamente através dela.  # Autenticação  Você precisa de um [HTTP BEARER TOKEN](https://oauth.net/2/bearer-tokens/) para identificar a conta que está realizando solicitações para a API. Você pode obter seu token de autenticação no seu [Painel do Cliente](https://face.himni.com.br/).  Insira seu token no campo que se encontra topo desta página para testar os métodos da API.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * FaceApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FaceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation personCreateFace
     *
     * Person - Create Face
     *
     * @param  string $person_uuid person_uuid (required)
     * @param  string $picture picture (optional)
     * @param  string $meta meta (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\PersonCreateFace
     */
    public function personCreateFace($person_uuid, $picture = null, $meta = null)
    {
        list($response) = $this->personCreateFaceWithHttpInfo($person_uuid, $picture, $meta);
        return $response;
    }

    /**
     * Operation personCreateFaceWithHttpInfo
     *
     * Person - Create Face
     *
     * @param  string $person_uuid (required)
     * @param  string $picture (optional)
     * @param  string $meta (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\PersonCreateFace, HTTP status code, HTTP response headers (array of strings)
     */
    public function personCreateFaceWithHttpInfo($person_uuid, $picture = null, $meta = null)
    {
        $returnType = '\Swagger\Client\Model\PersonCreateFace';
        $request = $this->personCreateFaceRequest($person_uuid, $picture, $meta);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\PersonCreateFace',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation personCreateFaceAsync
     *
     * Person - Create Face
     *
     * @param  string $person_uuid (required)
     * @param  string $picture (optional)
     * @param  string $meta (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function personCreateFaceAsync($person_uuid, $picture = null, $meta = null)
    {
        return $this->personCreateFaceAsyncWithHttpInfo($person_uuid, $picture, $meta)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation personCreateFaceAsyncWithHttpInfo
     *
     * Person - Create Face
     *
     * @param  string $person_uuid (required)
     * @param  string $picture (optional)
     * @param  string $meta (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function personCreateFaceAsyncWithHttpInfo($person_uuid, $picture = null, $meta = null)
    {
        $returnType = '\Swagger\Client\Model\PersonCreateFace';
        $request = $this->personCreateFaceRequest($person_uuid, $picture, $meta);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'personCreateFace'
     *
     * @param  string $person_uuid (required)
     * @param  string $picture (optional)
     * @param  string $meta (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function personCreateFaceRequest($person_uuid, $picture = null, $meta = null)
    {
        // verify the required parameter 'person_uuid' is set
        if ($person_uuid === null || (is_array($person_uuid) && count($person_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $person_uuid when calling personCreateFace'
            );
        }

        $resourcePath = '/persons/{person_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($person_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'person_uuid' . '}',
                ObjectSerializer::toPathValue($person_uuid),
                $resourcePath
            );
        }

        // form params
        if ($picture !== null) {
            $multipart = true;
            $formParams['picture'] = \GuzzleHttp\Psr7\try_fopen(ObjectSerializer::toFormValue($picture), 'rb');
        }
        // form params
        if ($meta !== null) {
            $formParams['meta'] = ObjectSerializer::toFormValue($meta);
        }
        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation personDeleteFace
     *
     * Person - Delete Face
     *
     * @param  string $person_uuid person_uuid (required)
     * @param  string $face_uuid face_uuid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function personDeleteFace($person_uuid, $face_uuid)
    {
        $this->personDeleteFaceWithHttpInfo($person_uuid, $face_uuid);
    }

    /**
     * Operation personDeleteFaceWithHttpInfo
     *
     * Person - Delete Face
     *
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function personDeleteFaceWithHttpInfo($person_uuid, $face_uuid)
    {
        $returnType = '';
        $request = $this->personDeleteFaceRequest($person_uuid, $face_uuid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation personDeleteFaceAsync
     *
     * Person - Delete Face
     *
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function personDeleteFaceAsync($person_uuid, $face_uuid)
    {
        return $this->personDeleteFaceAsyncWithHttpInfo($person_uuid, $face_uuid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation personDeleteFaceAsyncWithHttpInfo
     *
     * Person - Delete Face
     *
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function personDeleteFaceAsyncWithHttpInfo($person_uuid, $face_uuid)
    {
        $returnType = '';
        $request = $this->personDeleteFaceRequest($person_uuid, $face_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'personDeleteFace'
     *
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function personDeleteFaceRequest($person_uuid, $face_uuid)
    {
        // verify the required parameter 'person_uuid' is set
        if ($person_uuid === null || (is_array($person_uuid) && count($person_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $person_uuid when calling personDeleteFace'
            );
        }
        // verify the required parameter 'face_uuid' is set
        if ($face_uuid === null || (is_array($face_uuid) && count($face_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $face_uuid when calling personDeleteFace'
            );
        }

        $resourcePath = '/persons/{person_uuid}/{face_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($person_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'person_uuid' . '}',
                ObjectSerializer::toPathValue($person_uuid),
                $resourcePath
            );
        }
        // path params
        if ($face_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'face_uuid' . '}',
                ObjectSerializer::toPathValue($face_uuid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation personUpdateFace
     *
     * Person - Update Face
     *
     * @param  \Swagger\Client\Model\PersonUpdateFaceRequest $body body (required)
     * @param  string $person_uuid person_uuid (required)
     * @param  string $face_uuid face_uuid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\PersonUpdateFace
     */
    public function personUpdateFace($body, $person_uuid, $face_uuid)
    {
        list($response) = $this->personUpdateFaceWithHttpInfo($body, $person_uuid, $face_uuid);
        return $response;
    }

    /**
     * Operation personUpdateFaceWithHttpInfo
     *
     * Person - Update Face
     *
     * @param  \Swagger\Client\Model\PersonUpdateFaceRequest $body (required)
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\PersonUpdateFace, HTTP status code, HTTP response headers (array of strings)
     */
    public function personUpdateFaceWithHttpInfo($body, $person_uuid, $face_uuid)
    {
        $returnType = '\Swagger\Client\Model\PersonUpdateFace';
        $request = $this->personUpdateFaceRequest($body, $person_uuid, $face_uuid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\PersonUpdateFace',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation personUpdateFaceAsync
     *
     * Person - Update Face
     *
     * @param  \Swagger\Client\Model\PersonUpdateFaceRequest $body (required)
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function personUpdateFaceAsync($body, $person_uuid, $face_uuid)
    {
        return $this->personUpdateFaceAsyncWithHttpInfo($body, $person_uuid, $face_uuid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation personUpdateFaceAsyncWithHttpInfo
     *
     * Person - Update Face
     *
     * @param  \Swagger\Client\Model\PersonUpdateFaceRequest $body (required)
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function personUpdateFaceAsyncWithHttpInfo($body, $person_uuid, $face_uuid)
    {
        $returnType = '\Swagger\Client\Model\PersonUpdateFace';
        $request = $this->personUpdateFaceRequest($body, $person_uuid, $face_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'personUpdateFace'
     *
     * @param  \Swagger\Client\Model\PersonUpdateFaceRequest $body (required)
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function personUpdateFaceRequest($body, $person_uuid, $face_uuid)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling personUpdateFace'
            );
        }
        // verify the required parameter 'person_uuid' is set
        if ($person_uuid === null || (is_array($person_uuid) && count($person_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $person_uuid when calling personUpdateFace'
            );
        }
        // verify the required parameter 'face_uuid' is set
        if ($face_uuid === null || (is_array($face_uuid) && count($face_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $face_uuid when calling personUpdateFace'
            );
        }

        $resourcePath = '/persons/{person_uuid}/{face_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($person_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'person_uuid' . '}',
                ObjectSerializer::toPathValue($person_uuid),
                $resourcePath
            );
        }
        // path params
        if ($face_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'face_uuid' . '}',
                ObjectSerializer::toPathValue($face_uuid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation personViewFace
     *
     * Person - View Face
     *
     * @param  string $person_uuid person_uuid (required)
     * @param  string $face_uuid face_uuid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\PersonViewFace
     */
    public function personViewFace($person_uuid, $face_uuid)
    {
        list($response) = $this->personViewFaceWithHttpInfo($person_uuid, $face_uuid);
        return $response;
    }

    /**
     * Operation personViewFaceWithHttpInfo
     *
     * Person - View Face
     *
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\PersonViewFace, HTTP status code, HTTP response headers (array of strings)
     */
    public function personViewFaceWithHttpInfo($person_uuid, $face_uuid)
    {
        $returnType = '\Swagger\Client\Model\PersonViewFace';
        $request = $this->personViewFaceRequest($person_uuid, $face_uuid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\PersonViewFace',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation personViewFaceAsync
     *
     * Person - View Face
     *
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function personViewFaceAsync($person_uuid, $face_uuid)
    {
        return $this->personViewFaceAsyncWithHttpInfo($person_uuid, $face_uuid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation personViewFaceAsyncWithHttpInfo
     *
     * Person - View Face
     *
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function personViewFaceAsyncWithHttpInfo($person_uuid, $face_uuid)
    {
        $returnType = '\Swagger\Client\Model\PersonViewFace';
        $request = $this->personViewFaceRequest($person_uuid, $face_uuid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'personViewFace'
     *
     * @param  string $person_uuid (required)
     * @param  string $face_uuid (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function personViewFaceRequest($person_uuid, $face_uuid)
    {
        // verify the required parameter 'person_uuid' is set
        if ($person_uuid === null || (is_array($person_uuid) && count($person_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $person_uuid when calling personViewFace'
            );
        }
        // verify the required parameter 'face_uuid' is set
        if ($face_uuid === null || (is_array($face_uuid) && count($face_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $face_uuid when calling personViewFace'
            );
        }

        $resourcePath = '/persons/{person_uuid}/{face_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($person_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'person_uuid' . '}',
                ObjectSerializer::toPathValue($person_uuid),
                $resourcePath
            );
        }
        // path params
        if ($face_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'face_uuid' . '}',
                ObjectSerializer::toPathValue($face_uuid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
